OUTPUT_DIR: './test/lipo'
TAG: 'default'
SEED: 2021
NUM_FOLDS: 1
HYPER: True
HYPER_REMOVE: None
NUM_ITERS: 30


DATA:
  BATCH_SIZE: 64
  DATASET: 'lipo_1'
  DATA_PATH: './data/lipo_1/'
  TASK_TYPE: 'regression'
  METRIC: 'rmse'
  SPLIT_TYPE: 'random'
  

MODEL:
  F_ATT: False
  BRICS: False
  DEPTH: 2
  DROPOUT: 0.1
  SLICES: 4
  R: 2
  HID: 128

LOSS:
  FL_LOSS: False
  CL_LOSS: False


TRAIN:
  EARLY_STOP: 50
  MAX_EPOCHS: 200
  OPTIMIZER:
    TYPE: 'adam'
    BASE_LR: 0.00072
  LR_SCHEDULER:
    TYPE: 'reduce'
